cicd added

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -22,6 +22,9 @@ jobs:
       - name: Lint code
         run: echo "Linting repository"
 
+      - name: Run unit tests
+        run: echo "Running unit tests"
+
   build-and-push-ecr-image:
     name: Continuous Delivery
     needs: integration
@@ -41,14 +44,14 @@ jobs:
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1
 
-      - name: Build and Push
+      - name: Build, tag, and push image to Amazon ECR
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
         run: |
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
-
+          
   Continuous-Deployment:
     needs: build-and-push-ecr-image
     runs-on: self-hosted
@@ -62,21 +65,19 @@ jobs:
           ECR_REGISTRY: ${{ secrets.AWS_ECR_LOGIN_URI }}
           ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
         run: |
-          # 1. Pull the image
+          # Pull latest image
           docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest
           
-          # 2. Stop and remove only if the container exists (using new name)
-          if [ $(docker ps -a -q -f name=chicken-disease) ]; then
-            docker stop chicken-disease
-            docker rm chicken-disease
-          fi
+          # Stop and remove existing container if it exists
+          docker stop chicken || true
+          docker rm -f chicken || true
           
-          # 3. Run the new container with the new name
-          docker run -d -p 8080:8080 --name=chicken-disease \
+          # Run new container
+          docker run -d -p 8080:8080 --name=chicken \
             -e 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' \
             -e 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
             -e 'AWS_REGION=${{ secrets.AWS_REGION }}' \
             $ECR_REGISTRY/$ECR_REPOSITORY:latest
-          
-          # 4. Clean up
+            
+          # Clean up dangling images
           docker image prune -f
